# Numpy

---

## Introducción a NumPy

### ¿Qué es NumPy?

**NumPy** (del inglés *Numerical Python*) es una **biblioteca de Python** diseñada para trabajar con **arrays** (también llamados *vectores* o *matrices* de datos numéricos).

Además de manejar datos en forma de arrays, NumPy incluye muchas funciones matemáticas avanzadas:

* Álgebra lineal (matrices, vectores, determinantes...).
* Transformadas de Fourier.
* Operaciones con números complejos.

**Fue creada en 2005 por Travis Oliphant** y es un proyecto de **código abierto**, lo que significa que puedes usarla libremente y también contribuir a mejorarla.

---

### ¿Por qué usar NumPy?

En Python ya existen las **listas**, que pueden parecer similares a los arrays, pero hay una gran diferencia:
👉 **las listas son mucho más lentas** para cálculos numéricos.

NumPy proporciona un **objeto especial llamado `ndarray`** (abreviatura de *n-dimensional array*), que está diseñado para ejecutar operaciones **hasta 50 veces más rápido** que una lista tradicional.

Esto se debe a que:

* Los arrays de NumPy están **optimizados para cálculo numérico intensivo**.
* Incluyen **funciones vectorizadas**, que aplican operaciones a todos los elementos a la vez, sin bucles.
* Permiten aprovechar **la arquitectura del procesador (CPU)** de forma más eficiente.

💡 **En ciencia de datos e inteligencia artificial**, los arrays son fundamentales porque se trabaja constantemente con grandes volúmenes de números (imágenes, registros, medidas, etc.).
Cuanto más rápido se procesen, mejor.

---

*¿Qué es la ciencia de datos?*

La **ciencia de datos (Data Science)** es una rama de la informática que estudia **cómo almacenar, usar y analizar datos** para obtener conocimiento o tomar decisiones.



---

### ¿Por qué NumPy es más rápido que las listas?

La diferencia está en **cómo se guardan los datos en la memoria del ordenador**.

* Una **lista de Python** guarda los elementos de forma dispersa (cada número puede estar en una zona distinta de la memoria).
* Un **array de NumPy** guarda todos los datos **en un único bloque continuo** de memoria.

Esto permite al procesador:

* Acceder a los datos más rápidamente.
* Aplicar operaciones matemáticas a todos los elementos sin repetir pasos innecesarios.

Este principio se llama **localidad de referencia**, y es clave para entender por qué NumPy es tan veloz.

---

### ¿En qué lenguaje está escrito NumPy?

Aunque tú lo usas desde Python, **la mayor parte del código de NumPy está escrita en C y C++**, lenguajes mucho más rápidos.
Python actúa como una “capa amigable” para que podamos usar esa potencia sin complicarnos con código bajo nivel.

---

### ¿Dónde se encuentra el código de NumPy?

NumPy es **software libre y colaborativo**.
Su código fuente está disponible en GitHub:
🔗 [https://github.com/numpy/numpy](https://github.com/numpy/numpy)

GitHub es una plataforma donde desarrolladores de todo el mundo pueden trabajar juntos en un mismo proyecto, añadir mejoras y corregir errores.

---



## Empezando con NumPy 🚀

### Instalación de NumPy

Si ya tienes **Python** y **PIP** instalados en tu ordenador, instalar NumPy es muy sencillo.

Abre una **terminal** (o el símbolo del sistema en Windows) y escribe:


In [ ]:
pip install numpy

Si usas **Google Colab**, no necesitas instalar nada: NumPy ya viene incluido.
Si trabajas en **VS Code**, **Jupyter Notebook** o **Anaconda**, también suele venir preinstalado.

En caso de que el comando falle, puedes instalar una **distribución de Python** que ya incluya NumPy y otras herramientas científicas:

* [Anaconda](https://www.anaconda.com/)
* [Spyder](https://www.spyder-ide.org/)
* [Google Colab](https://colab.research.google.com)

### Importar NumPy en tu programa

Una vez instalado, para usar NumPy debes **importarlo** en tu código con la palabra clave `import`

In [ ]:
import numpy

A partir de este momento, puedes acceder a todas las funciones de NumPy.

Ejemplo:

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

### Usar un alias: `np`

En casi todos los programas verás que NumPy se importa con un **alias**, normalmente `np`.
Esto ahorra tiempo al escribir y hace el código más limpio.

👉 *Un alias* en Python es simplemente un **nombre alternativo** para referirse a la misma librería u objeto.

Ejemplo:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

Ahora puedes escribir `np.array()` en lugar de `numpy.array()`.
Ambos significan lo mismo.

---

### Comprobar la versión instalada

Si quieres saber qué versión de NumPy estás utilizando, puedes hacerlo con el atributo especial `__version__`:

In [ ]:
import numpy as np

print(np.__version__)

## Creación de Arrays en NumPy

### El objeto principal: `ndarray`

NumPy se usa para trabajar con **arrays**, que son estructuras donde guardamos **muchos valores numéricos** juntos (como listas, pero mucho más rápidas).

El objeto que representa un array en NumPy se llama **`ndarray`**, que significa *N-dimensional array*.

Podemos crear un `ndarray` usando la función `np.array()`.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))

👉 La función integrada `type()` nos dice el tipo de objeto.
En este caso, `arr` es de tipo `numpy.ndarray`.

---

### Crear un array a partir de otros tipos

Puedes pasarle a `np.array()`:

* una **lista** (`[ ]`),
* una **tupla** (`( )`),
* o incluso otro **array**.

NumPy los convierte automáticamente en un `ndarray`.

Ejemplo (usando una tupla):

In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)

---

## Dimensiones en los arrays

Cada **nivel de anidamiento** dentro de un array se llama **dimensión**.

👉 Un *array anidado* (o *nested array*) es aquel que contiene otros arrays dentro.

| Nivel | Tipo de array | Descripción breve             |
| ----- | ------------- | ----------------------------- |
| 0-D   | Escalar       | Un solo valor.                |
| 1-D   | Vector        | Una lista de números.         |
| 2-D   | Matriz        | Una tabla (filas y columnas). |
| 3-D   | Tensor        | Varias matrices juntas.       |

---

### 0-D (Escalar)

Un **0-D array** contiene un único valor, por ejemplo un número.

In [ ]:
import numpy as np
arr = np.array(42)
print(arr)

Cada número individual dentro de un array puede verse como un *array 0-D*.

---

### 1-D (Vector)

Un **array unidimensional** tiene varios valores en una sola línea, como una lista.


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

Es el tipo más común y básico de array.

---

### 2-D (Matriz)

Un **array bidimensional** tiene filas y columnas, igual que una tabla o una hoja de cálculo.
Cada fila es un array 1-D.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

 En álgebra lineal, esto se conoce como una **matriz**.
NumPy incluye un submódulo específico para matrices (`numpy.mat`).

---

### 3-D (Tensor)

Un **array tridimensional** contiene varias matrices.
Este tipo de estructura se usa mucho en **Inteligencia Artificial**, especialmente con imágenes (que tienen alto, ancho y canales de color).

In [ ]:
import numpy as np
arr = np.array([
  [[1, 2, 3], [4, 5, 6]],
  [[1, 2, 3], [4, 5, 6]]
])
print(arr)

---

### Comprobar el número de dimensiones

Cada array de NumPy tiene un atributo especial llamado **`.ndim`**, que indica cuántas dimensiones tiene.

Ejemplo:

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([
  [[1, 2, 3], [4, 5, 6]],
  [[1, 2, 3], [4, 5, 6]]
])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

---

### Arrays de más dimensiones

NumPy permite crear arrays con **tantas dimensiones como necesites**.
Esto se define con el parámetro `ndmin`.

Ejemplo:

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Número de dimensiones:', arr.ndim)

[[[[[1 2 3 4]]]]]
Número de dimensiones: 5


Aquí:

* La 5ª dimensión tiene 4 elementos (los números).
* La 4ª contiene ese vector.
* La 3ª es una matriz que lo incluye.
* La 2ª y 1ª son niveles superiores que envuelven todo el conjunto.

💡 En IA, estas estructuras se utilizan para representar **tensores** de datos (por ejemplo, una colección de imágenes o secuencias temporales).

---

### Resumen

| Dimensión | Forma del array              | Ejemplo en Python                                     | Representación |
| --------- | ---------------------------- | ----------------------------------------------------- | -------------- |
| 0-D       | `()`                         | `np.array(7)`                                         | `7`            |
| 1-D       | `(n,)`                       | `np.array([1,2,3])`                                   | `[1 2 3]`      |
| 2-D       | `(filas, columnas)`          | `np.array([[1,2,3],[4,5,6]])`                         | tabla          |
| 3-D       | `(bloques, filas, columnas)` | `np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])` | cubo           |
| n-D       | `(dim1, dim2, ..., dimN)`    | `np.array([1,2], ndmin=5)`                            | tensor         |

---

## <font color="red"> Actividad práctica 1</font>

1. Crea en tu entorno tres arrays diferentes:

   * Un escalar (0-D) con el número 10.
   * Un vector (1-D) con los números del 1 al 5.
   * Una matriz (2-D) de dos filas y tres columnas con los números del 1 al 6.
2. Muestra el número de dimensiones (`.ndim`) de cada uno.
3. Usa `ndmin=4` para crear un array con 4 dimensiones y explora su forma.
4. Explica con tus palabras qué significa “dimensión” en un array.

---

In [ ]:
import numpy
#Escalar
escalar = numpy.array(10)
print(escalar)

#Vector
vector = numpy.array([1,2,3,4,5])
print(vector)
#Matriz
matriz = numpy.array([[1,2,3],
                     [4,5,6]])
print(matriz)
#Ejercicio 2
print(matriz.ndim,vector.ndim,escalar.ndim)
#Ejercicio 3
arr = numpy.array([1, 2, 3, 4], ndmin=4)
print(arr)
#Ejercicio4
print("Es el numero de filas por columnas que tiene")

10
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
2 1 0
[[[[[1 2 3 4]]]]]


# Indexación en Arrays de NumPy

## Acceder a elementos de un array

La **indexación** consiste en acceder a los valores individuales dentro de un array.
Funciona de forma muy parecida a las **listas de Python**.

📌 En NumPy, los índices **comienzan en 0**:

* El primer elemento tiene índice `0`.
* El segundo elemento tiene índice `1`.
* El tercero tiene índice `2`, y así sucesivamente.

---

## Ejemplo básico (1-D)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])  # Primer elemento

---

### Acceder a distintos elementos

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])        # Segundo elemento → 2
print(arr[2] + arr[3])  # Suma del 3º y 4º elementos → 7

Recuerda:
`arr[índice]` devuelve el elemento en la posición indicada.

---

## Indexación en Arrays 2-D (matrices)

Los arrays de **dos dimensiones** se pueden imaginar como **tablas con filas y columnas**.

Para acceder a un elemento: usamos una pareja de índices separados por coma:

```python
arr[fila, columna]
```
Ejemplo:


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print("2º elemento de la 1ª fila:", arr[0, 1])

Otro ejemplo:

In [ ]:
print("5º elemento de la 2ª fila:", arr[1, 4])


 Piensa que:

* El **primer índice** selecciona la **fila**.
* El **segundo índice** selecciona la **columna** dentro de esa fila.

---

## Indexación en Arrays 3-D (tensores)

Los arrays de tres dimensiones pueden verse como **bloques de datos**, donde cada bloque contiene matrices.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])

print(arr[0, 1, 2])

### Explicación paso a paso

1️⃣ `arr[0]` selecciona el **primer bloque**:

```
[[1, 2, 3],
 [4, 5, 6]]
```

2️⃣ `arr[0, 1]` selecciona la **segunda fila** dentro de ese bloque:

```
[4, 5, 6]
```

3️⃣ `arr[0, 1, 2]` selecciona el **tercer valor** de esa fila:

```
6
```

---

## Indexación negativa

También puedes acceder a los elementos **desde el final** del array usando índices **negativos**.

* `-1` → último elemento
* `-2` → penúltimo elemento, etc.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print("Último elemento de la 2ª fila:", arr[1, -1])

### Resumen rápido

| Tipo de array | Ejemplo de acceso       | Devuelve                                       |
| ------------- | ----------------------- | ---------------------------------------------- |
| 1-D           | `arr[2]`                | 3er elemento                                   |
| 2-D           | `arr[1, 4]`             | Elemento en fila 2 columna 5                   |
| 3-D           | `arr[0, 1, 2]`          | Valor dentro del bloque 1 → fila 2 → columna 3 |
| Negativo      | `arr[-1]`, `arr[1, -1]` | Último elemento                                |

---

## <font color="red"> Actividad práctica 2</font>

1. Crea el siguiente array en tu entorno:

   ```python
   import numpy as np
   arr = np.array([[10, 20, 30, 40],
                   [50, 60, 70, 80]])
   ```
2. Muestra:

   * El primer elemento.
   * El valor en la 2ª fila, 3ª columna.
   * El último valor usando índice negativo.
3. Crea un array 3-D sencillo y accede a un valor dentro de la segunda “capa”.
4. Explica con tus palabras cómo cambian los índices según la dimensión.


In [51]:
#Ejercicio 2
import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])
print(arr[0][0])
print(arr[1][2])
print(arr[-1][-1])
#Ejercicio3
arr = np.array([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(arr.ndim)
print(arr[1][1][0])

#Ejercicio 4
print("Segun la dimension, las indices cambian de la siguiente manera, indicando primero la fila, luego lsa columnas y luego el elemento de la capa")

10
70
80
3
10
Segun la dimension, las indices cambian de la siguiente manera, indicando primero la fila, luego lsa columnas y luego el elemento de la capa


# Rebanado (Slicing) en Arrays de NumPy 

## ¿Qué es el *slicing*?

El **slicing** (o *rebanado*) permite **extraer una parte de un array**, seleccionando un rango de índices.

En lugar de acceder a un único elemento (`arr[3]`), usamos una **secuencia de índices** con esta sintaxis:

```python
[start:end]
```

También podemos indicar un **salto (step)**:

```python
[start:end:step]
```

---

## Reglas básicas

| Parámetro | Significado                               | Valor por defecto  |
| --------- | ----------------------------------------- | ------------------ |
| `start`   | Índice donde comienza el corte (incluido) | 0                  |
| `end`     | Índice donde termina el corte (excluido)  | longitud del array |
| `step`    | Tamaño del salto entre elementos          | 1                  |

👉 El elemento del índice final (`end`) **no se incluye** en el resultado.

---

### Ejemplo 1 — De índice 1 a 5


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

---

### Ejemplo 2 — Desde el índice 4 hasta el final

In [ ]:
array2 = array[array > 30]  # Filtrar elementos mayores que 30
array2

---

### Ejemplo 3 — Desde el inicio hasta el índice 4 (no incluido)

In [ ]:
print(arr[:4])


---

## Slicing negativo

También puedes usar **índices negativos** para contar desde el final.

Por ejemplo:

* `-1` → último elemento
* `-2` → penúltimo elemento

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

Empieza desde el tercer elemento contando desde el final (`-3`)
y termina en el índice `-1` (sin incluirlo).

---

## Usar pasos (*step*)

El tercer parámetro permite **saltar elementos** dentro del rango.

### Ejemplo 1 — Saltos de 2 posiciones entre índices 1 y 5

In [ ]:
print(arr[1:5:2])


El `::2` significa:

> “Desde el principio hasta el final, tomando un elemento sí y otro no”.

---

## Slicing en arrays 2-D

En los arrays bidimensionales, el *slicing* funciona igual, pero podemos aplicarlo **por filas y columnas**.

---

### Ejemplo 1 — Cortar una fila

Extraer desde la segunda fila (`índice 1`), los elementos entre el índice 1 y 4 (no incluido):


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

---

### Ejemplo 2 — Obtener una sola columna de varias filas

In [ ]:
print(arr[0:2, 2])


Aquí `arr[0:2, 2]` significa:

> “De las filas 0 a 1, selecciona la columna 2”.

---

### Ejemplo 3 — Seleccionar submatriz (rango en filas y columnas)


In [ ]:
print(arr[0:2, 1:4])


Esto devuelve un **array 2-D**, formado por el bloque de datos de esas posiciones.

---

###  Resumen visual

| Ejemplo         | Resultado     | Descripción                 |
| --------------- | ------------- | --------------------------- |
| `arr[1:5]`      | `[2 3 4 5]`   | Del índice 1 al 4           |
| `arr[:3]`       | `[1 2 3]`     | Desde el inicio hasta el 3º |
| `arr[::2]`      | `[1 3 5 7]`   | Cada dos elementos          |
| `arr[-3:-1]`    | `[5 6]`       | Desde el final              |
| `arr[1, 1:4]`   | `[7 8 9]`     | Slicing en fila             |
| `arr[0:2, 1:4]` | Submatriz 2x3 | Fila y columna a la vez     |

---

## <font color="red"> Actividad práctica 3</font>

1. Crea el array:

   ```python
   import numpy as np
   arr = np.array([10, 20, 30, 40, 50, 60, 70])
   ```

   y muestra:

   * Los elementos del índice 2 al 5.
   * Los elementos desde el principio hasta el índice 4.
   * Los elementos en posiciones pares ``[10 30 50 70]``.

2. Crea una matriz:

   ```python
   m = np.array([[11, 12, 13, 14],
                 [21, 22, 23, 24],
                 [31, 32, 33, 34]])
   ```

   y muestra:

   * La segunda fila ``[21 22 23 24]``.
   * La segunda columna ``[12 22 32]``.
   * El bloque central
     ````
       [[12 13]     
       [22 23]]
    ````

3. Explica con tus palabras qué diferencia hay entre **indexar** y **rebanar** un array.

In [86]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[2:5])
print(arr[:4])
print(arr[0:len(arr):2])
#Ejercicio 2
m = np.array([[11, 12, 13, 14],
            [21, 22, 23, 24],
            [31, 32, 33, 34]])
print(m[1])
print(m[0:3,1])
print(m[0][1:3],"\n",m[1][1:3])
print(m[0:2,1:3])
print("Indexar es coger un valor y rebanar es obtener una secuencia de valores")

[30 40 50]
[10 20 30 40]
[10 30 50 70]
[21 22 23 24]
[12 22 32]
[12 13] 
 [22 23]
[[12 13]
 [22 23]]
Indexar es coger un valor y rebanar es obtener una secuencia de valores


# Tipos de datos en NumPy 

## Tipos de datos básicos en Python

Antes de ver NumPy, recordemos los tipos de datos que ya existen en **Python**:

| Tipo               | Descripción                    | Ejemplo              |
| ------------------ | ------------------------------ | -------------------- |
| **string (str)**   | Texto entre comillas           | `"Hola"`, `'Python'` |
| **integer (int)**  | Números enteros                | `-3`, `0`, `25`      |
| **float**          | Números reales (con decimales) | `3.14`, `42.0`       |
| **boolean (bool)** | Verdadero o falso              | `True`, `False`      |
| **complex**        | Números complejos              | `1 + 2j`, `3.5 + 4j` |

---

## Tipos de datos en NumPy

NumPy amplía estos tipos con otros más específicos y optimizados para cálculos numéricos.
Cada tipo se identifica con **un carácter** que representa su categoría.

| Código | Tipo de dato                             | Ejemplo                        |
| ------ | ---------------------------------------- | ------------------------------ |
| `i`    | Entero con signo                         | `-10`, `25`                    |
| `u`    | Entero sin signo (no puede ser negativo) | `0`, `255`                     |
| `f`    | Número real (float)                      | `3.1416`                       |
| `c`    | Número complejo                          | `2+3j`                         |
| `b`    | Booleano                                 | `True`, `False`                |
| `S`    | Cadena de texto (bytes)                  | `b"hola"`                      |
| `U`    | Cadena Unicode                           | `"hola"`                       |
| `m`    | Diferencia de tiempo (*timedelta*)       | `1 día`                        |
| `M`    | Fecha y hora (*datetime*)                | `2025-10-06`                   |
| `O`    | Objeto Python                            | cualquier tipo                 |
| `V`    | Bloque fijo de memoria (*void*)          | reservado para usos especiales |

---

### Comprobar el tipo de datos de un array

Cada array NumPy tiene una propiedad llamada `.dtype` que indica el tipo de datos de sus elementos.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

---

Ejemplo con cadenas:

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

Significa “Unicode string” de longitud máxima 6.

---

## Crear arrays con un tipo de dato definido

Podemos indicar el tipo de datos al crear el array usando el argumento **`dtype`**.

### Ejemplo 1 — Array de cadenas

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

Los valores se han convertido en **bytes** (`b'...'`).

---

### Ejemplo 2 — Array de enteros de 4 bytes

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

En este caso, `'i4'` significa:

* `i` → entero con signo
* `4` → ocupa 4 bytes (32 bits)

---

###  Si un valor no puede convertirse

NumPy mostrará un **ValueError** si el tipo de datos no es compatible.

Ejemplo:

In [ ]:
arr = np.array(['a', '2', '3'], dtype='i')


Esto ocurre porque `'a'` no puede convertirse a número entero.

---

## Convertir el tipo de datos de un array existente

Para cambiar el tipo de un array ya creado, se usa el método **`.astype()`**.

Este método **crea una copia** del array con el nuevo tipo de datos.

---

### Ejemplo 1 — De float a int

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

---

### Ejemplo 2 — Usando el tipo directamente (`int`)


In [ ]:
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

---

### Ejemplo 3 — De entero a booleano

In [ ]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

En este caso, `0` → `False` y cualquier otro número → `True`.

---

###  Resumen visual

| Operación            | Ejemplo                        | Resultado           | Tipo (`dtype`) |     |
| -------------------- | ------------------------------ | ------------------- | -------------- | --- |
| Tipo automático      | `np.array([1,2,3])`            | `[1 2 3]`           | `int64`        |     |
| Forzar tipo texto    | `np.array([1,2,3], dtype='S')` | `[b'1' b'2' b'3']`  | `              | S1` |
| Enteros de 4 bytes   | `dtype='i4'`                   | `[1 2 3 4]`         | `int32`        |     |
| Cambiar tipo         | `.astype('f')`                 | `[1. 2. 3.]`        | `float32`      |     |
| De entero a booleano | `.astype(bool)`                | `[True False True]` | `bool`         |     |

---

## <font color="red"> Actividad práctica 4</font>

1. Crea un array con los valores `[10.5, 20.1, 30.9]` y muéstralo con su tipo de datos.
2. Convierte ese array a **entero** con `.astype(int)` y observa los resultados.
3. Crea un array de tipo **cadena (`dtype='U'`)** con los valores `['rojo', 'verde', 'azul']` y muestra su tipo.
4. Crea un array con `[1, 0, 5, 0, 3]` y conviértelo a **booleano**.
5. Explica con tus palabras por qué es importante definir correctamente el tipo de datos en cálculos de IA o Big Data.

In [1]:
import numpy as np
arr = np.array([10.5,20.1,30.9])
print(arr.dtype)

#Ejercicio 2
arr = arr.astype(int)
print(arr.dtype)
#Ejercicio 3
array = np.array(["rojo","verde","azul"])
print(array.dtype)
array1 = np.array([1,0,5,0,3])
array1 = array1.astype(bool)
print(array1.dtype)
print("Los algoritmos de IA necesitan datos limpios y bien definidos. Si los tipos no están claros,El modelo puede aprender mal (por ejemplo, interpretar un número como texto).")

float64
int64
<U5
bool
Los algoritmos de IA necesitan datos limpios y bien definidos. Si los tipos no están claros,El modelo puede aprender mal (por ejemplo, interpretar un número como texto).


# Copias y Vistas en NumPy 

## Diferencia entre **copy()** y **view()**

Cuando trabajamos con arrays en NumPy, es importante saber si los datos se **copian** o solo se **comparten** entre variables.

| Tipo                 | Qué hace                                                 | Cambios afectan al original |
| -------------------- | -------------------------------------------------------- | --------------------------- |
| **Copy** (`.copy()`) | Crea un **nuevo array independiente**.                   | ❌ No                        |
| **View** (`.view()`) | Crea una **vista** del mismo array (comparte los datos). | ✅ Sí                        |

En resumen:

* Una **copia** tiene sus propios datos.
* Una **vista** solo muestra los datos del original.

---

### Ejemplo 1 — Copy (copia independiente)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()       # Creamos una copia

arr[0] = 42          # Cambiamos el original

print("Array original:", arr)
print("Copia:", x)

Observa que el cambio en `arr` **no afecta** a `x`.

---

## Ejemplo 2 — View (vista compartida)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()       # Creamos una vista

arr[0] = 42          # Cambiamos el original

print("Array original:", arr)
print("Vista:", x)

En este caso, la **vista refleja los cambios** hechos en el original.

---

## Ejemplo 3 — Cambiar la vista también cambia el original

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

x[0] = 31            # Cambiamos la vista

print("Array original:", arr)
print("Vista:", x)

Como `x` es una vista, ambos comparten el mismo espacio de memoria.

---

## Verificar si un array **posee sus propios datos**

Cada array NumPy tiene un atributo especial llamado **`.base`**.

* Si `.base` devuelve `None`, el array **posee sus propios datos** (es una copia).
* Si `.base` devuelve otro array, significa que **es una vista** de ese array original.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print("Base de x:", x.base)
print("Base de y:", y.base)

Esto indica que:

* `x` (copy) **no depende de nadie**.
* `y` (view) **depende de `arr`**, ya que comparte sus datos.

---

###  Resumen visual

| Método    | Independiente del original | Cambios compartidos | `.base`                | Uso típico                                   |
| --------- | -------------------------- | ------------------- | ---------------------- | -------------------------------------------- |
| `.copy()` | ✅ Sí                       | ❌ No                | `None`                 | Cuando quieres trabajar con una copia segura |
| `.view()` | ❌ No                       | ✅ Sí                | referencia al original | Cuando solo necesitas leer o ver los datos   |

---

## <font color="red"> Actividad práctica 5</font>

1. Crea el array:

   ```python
   arr = np.array([10, 20, 30, 40])
   ```

   * Haz una **copia** y una **vista**.
   * Modifica el primer elemento de `arr`.
   * Observa qué cambia en cada uno.

2. Usa `.base` para comprobar cuál de los dos (`copy` o `view`) posee sus datos.

3. Cambia un valor dentro de la **vista** y comprueba si el cambio afecta al original.

4. Reflexiona 💬
   ¿Por qué crees que NumPy ofrece las “vistas”?
   *(Pista: piensa en la eficiencia y en trabajar con arrays muy grandes).*

In [4]:
import numpy as np
#Ejercicio 1
arr = np.array([10, 20, 30, 40])
copia = arr.copy()
vista = arr.view()
print(copia,vista)
#Ejercicio 2
arr[0] = 20
print(arr)
print(copia.base)
print(vista.base)

[10 20 30 40] [10 20 30 40]
[20 20 30 40]
None
[20 20 30 40]


# Forma de un Array en NumPy 

## (*Array Shape*)

---

## ¿Qué significa la “forma” de un array?

La **forma** (*shape*) de un array indica **cuántos elementos hay en cada dimensión**.
Se expresa mediante una **tupla** de números, uno por cada dimensión del array.

Por ejemplo:

* Un vector (1-D) tiene solo una dimensión: su longitud.
* Una matriz (2-D) tiene dos dimensiones: **número de filas** y **número de columnas**.
* Un tensor (3-D o más) tiene más dimensiones anidadas.

---

##  Obtener la forma de un array

NumPy ofrece el atributo `.shape`, que devuelve una **tupla** con el número de elementos en cada dimensión.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr.shape)

Esto significa que:

* La **primera dimensión** (filas) tiene 2 elementos.
* La **segunda dimensión** (columnas) tiene 4 elementos.

Por tanto, el array tiene forma **2x4**.

---

### 🔹 Ejemplo visual

| Fila | Elementos  |
| ---- | ---------- |
| 0    | 1  2  3  4 |
| 1    | 5  6  7  8 |

Forma: `(2, 4)`
→ 2 filas × 4 columnas

---

### Crear arrays con varias dimensiones

Podemos usar el argumento `ndmin` al crear el array para **forzar** un número mínimo de dimensiones.

Ejemplo:


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print("Forma del array:", arr.shape)

En este caso:

* El array tiene **5 dimensiones**.
* La última (5ª) dimensión contiene **4 elementos**.

---

###  Interpretación de `.shape`

Cada número dentro de la tupla indica **cuántos elementos tiene esa dimensión**.

Ejemplo:

| Dimensión | Valor en `shape` | Significado                            |
| --------- | ---------------- | -------------------------------------- |
| 1ª        | `1`              | Hay 1 bloque superior                  |
| 2ª        | `1`              | Dentro de ese bloque, hay 1 sub-bloque |
| 3ª        | `1`              | Dentro de ese sub-bloque, hay 1 matriz |
| 4ª        | `1`              | Dentro de la matriz, hay 1 fila        |
| 5ª        | `4`              | Y en esa fila hay 4 valores            |

Así, la **tupla `(1, 1, 1, 1, 4)`** nos dice que el array tiene 5 niveles de profundidad.

---

###  Resumen visual

| Tipo de array | Ejemplo                          | Forma (`.shape`)  |
| ------------- | -------------------------------- | ----------------- |
| 1-D (vector)  | `[1, 2, 3, 4]`                   | `(4,)`            |
| 2-D (matriz)  | `[[1,2,3],[4,5,6]]`              | `(2, 3)`          |
| 3-D (tensor)  | `[[[1,2],[3,4]], [[5,6],[7,8]]]` | `(2, 2, 2)`       |
| 5-D           | `np.array([1,2,3,4], ndmin=5)`   | `(1, 1, 1, 1, 4)` |

---

## <font color="red"> Actividad práctica 6</font>

1. Crea los siguientes arrays y muestra su `.shape`:

   ```python
   import numpy as np

   a = np.array([10, 20, 30])
   b = np.array([[1, 2, 3], [4, 5, 6]])
   c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
   ```

2. Explica qué significa cada número en la tupla `shape` de `a`, `b` y `c`.

3. Crea un array con `ndmin=4` y analiza su estructura.

4. Reflexiona 

   ¿Por qué crees que conocer la forma de un array es importante cuando trabajamos con **modelos de IA o redes neuronales**?


In [8]:
import numpy as np
a = np.array([10, 20, 30])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a.shape)
print(b.shape)
print(c.shape)
print("a es 1D con 3 elementos. b es 2D con 2 filas y 3 columnas.c es 3D con 2 bloques de 2 filas y 2 columnas cada uno")
arr = np.array([1, 2, 3, 4], ndmin=4)
print(arr.shape)
print("Para hacer operaciones con matrices siendo estas compatibles")


(3,)
(2, 3)
(2, 2, 2)
a es 1D con 3 elementos. b es 2D con 2 filas y 3 columnas.c es 3D con 2 bloques de 2 filas y 2 columnas cada uno
(1, 1, 1, 4)
Para hacer operaciones con matrices siendo estas compatibles


# Redimensionamiento de Arrays en NumPy 

## (*Array Reshaping*)

---

## ¿Qué significa “reshape”?

**Reshaping** (redimensionar) significa **cambiar la forma** de un array, es decir, modificar **cuántos elementos hay en cada dimensión** sin alterar los datos originales.

Recordemos:

La **forma (shape)** de un array indica el número de elementos por dimensión.
Con `.reshape()` podemos:

* Añadir o quitar dimensiones.
* Reorganizar los datos en una estructura diferente.

➡️ **Muy habitual en Machine Learning para adaptar los datos a la forma esperada por el modelo.**

Se usa cuando necesitamos cambiar la estructura del array sin modificar sus valores, por ejemplo:

* Convertir un vector 1D en una matriz 2D (`(n_muestras, n_características)`).
* Aplanar o reconstruir datos tras unir, dividir o filtrar.
* Preparar las entradas de los modelos (por ejemplo, en regresión o redes neuronales).

---

#### 🔹 De 1-D a 2-D

Podemos convertir un **array unidimensional** (1-D) en uno **bidimensional** (2-D).

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

Aquí:

* El array original tiene 12 elementos.
* El nuevo tiene **4 filas × 3 columnas** → `(4, 3)` = 12 elementos totales.

---

#### 🔹 De 1-D a 3-D

También podemos crear arrays tridimensionales (3-D), útiles en *Machine Learning* o *procesamiento de imágenes*.

Ejemplo:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

Significa:

* 2 bloques,
* cada bloque con 3 filas,
* y cada fila con 2 columnas → **2×3×2 = 12 elementos**.

---

#### ❌ No todas las formas son posibles

Solo podemos usar `.reshape()` si el **número total de elementos** coincide antes y después.

Ejemplo que da error:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)  # ❌ Error: 8 ≠ 9

NumPy mostrará:

```
ValueError: cannot reshape array of size 8 into shape (3,3)
```

---

#### 🔍 ¿Copia o vista?

Por defecto, `reshape()` devuelve una **vista (view)** del array original si es posible.

Podemos comprobarlo con el atributo `.base`:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

 Devuelve el array original → es una **vista**, no una copia.
Si modificas el nuevo array, también cambia el original.

---

#### 🔸 Dimensión desconocida (-1)

Podemos dejar que NumPy **calcule automáticamente** una de las dimensiones usando `-1`.

Ejemplo:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)

Aquí NumPy calculó que la última dimensión debía ser 2, porque:
`2 × 2 × 2 = 8` elementos totales.

📌 Solo se puede usar **un -1** por reshape.

---

#### 🔻 Aplanar (Flattening)

“Aplanar” un array significa **convertir un array multidimensional en uno de una sola dimensión (1-D)**.

Podemos hacerlo con:

```python
newarr = arr.reshape(-1)
```

Ejemplo:

In [9]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


También existen otros métodos como `flatten()` o `ravel()`, pero `reshape(-1)` es el más sencillo y directo.

---

###  Resumen visual

| Operación             | Código                         | Resultado / Forma               |
| --------------------- | ------------------------------ | ------------------------------- |
| 1-D → 2-D             | `reshape(4,3)`                 | `(4,3)`                         |
| 1-D → 3-D             | `reshape(2,3,2)`               | `(2,3,2)`                       |
| Forma incorrecta      | `reshape(3,3)` con 8 elementos | ❌ Error                         |
| Vista del original    | `.reshape(...).base`           | Muestra el array original       |
| Dimensión desconocida | `reshape(2,2,-1)`              | NumPy calcula el valor faltante |
| Aplanar               | `reshape(-1)`                  | `(n,)` vector 1D                |

---

## <font color="red"> Actividad práctica 6</font>

1. Crea un array con los números del 1 al 12.

   * Conviértelo en un array 3×4.
   * Luego conviértelo en un array 2×3×2.
   * Comprueba sus `.shape` en cada caso.

2. Prueba a aplicar `reshape(3,3)` sobre un array con 8 elementos y observa el error que aparece.

3. Usa `reshape(2, -1)` sobre el array `[1,2,3,4,5,6]` y explica qué hace NumPy con el `-1`.

4. Convierte una matriz 2-D cualquiera en un array 1-D usando `reshape(-1)` y dibuja su estructura antes y después.

In [21]:
import numpy as np
#Ejercicio 1
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4, 3)
print(newarr)
print(arr.shape, newarr.shape)

#Ejercicio 2
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1.reshape(3,3)
print(arr1)
print(arr1.shape)
print("cannot reshape array of size 8 into shape (3,3)")

arr2 = np.array([1,2,3,4,5,6])
print(arr2)
print(arr2.reshape(2,-1))
print("Calcula el tamaño de la matriz para tener dos filas")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(12,) (4, 3)
[1 2 3 4 5 6 7 8 9]
(9,)
cannot reshape array of size 8 into shape (3,3)
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
Calcula el tamaño de la matriz para tener dos filas


# Iteración en Arrays de NumPy

## (*Array Iterating*)

---

## ¿Qué significa “iterar”?

**Iterar** significa **recorrer los elementos de un array uno por uno**.
En Python, esto se hace normalmente con un **bucle `for`**, y NumPy permite hacerlo con arrays de cualquier número de dimensiones.

---

### 🔹 Iterar sobre un array 1-D

Cuando recorremos un array unidimensional, el bucle pasa por **cada elemento** de manera secuencial.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

Este tipo de bucle es idéntico al de una lista de Python.

---

#### 🔹 Iterar sobre un array 2-D

En un array bidimensional, el bucle recorre **cada fila** (no los elementos individuales todavía).

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in arr:
    print(x)

Cada `x` es una **submatriz 1-D** (una fila del array).

---

#####  Recorrer cada elemento (escalares)

Para acceder a los valores individuales, se anidan bucles:

In [ ]:
for x in arr:
    for y in x:
        print(y)

---

#### 🔹 Iterar sobre un array 3-D

Un array tridimensional contiene **matrices 2-D** en su interior.

In [ ]:
import numpy as np

arr = np.array([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])

for x in arr:
    print(x)

---

#####  Recorrer todos los valores escalares

Para llegar hasta los números individuales:

In [ ]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

Cada nivel del bucle accede a una dimensión más profunda.

---

#### Usar `np.nditer()` (Iterador avanzado)

Cuando el array tiene muchas dimensiones, escribir bucles anidados se vuelve complicado.
Para eso, NumPy ofrece **`np.nditer()`**, que permite recorrer todos los elementos (escalares) **sin importar la cantidad de dimensiones**.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([
  [[1, 2], [3, 4]],
  [[5, 6], [7, 8]]
])

for x in np.nditer(arr):
    print(x)

`nditer()` recorre **todos los elementos** del array, sin importar su forma.

---

#### Cambiar el tipo de dato durante la iteración

Podemos usar el argumento `op_dtypes` para transformar temporalmente los tipos de dato mientras iteramos.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

Se convierten los valores numéricos en cadenas de texto (`bytes`).

El parámetro `flags=['buffered']` permite crear un **espacio temporal** para convertir los datos sin modificar el array original.

---

#### Iterar con paso (step)

Podemos combinar **rebanado (slicing)** con la iteración.

Ejemplo:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

Aquí `arr[:, ::2]` selecciona **todas las filas** pero **solo las columnas pares** (saltando de 2 en 2).

---

#### Iteración con índices → `np.ndenumerate()`

Si además de los valores quieres saber **la posición (índice)** de cada elemento, usa `ndenumerate()`.

##### Ejemplo 1 — Array 1-D

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

---

####  Ejemplo 2 — Array 2-D

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

Cada tupla `(fila, columna)` indica la posición del valor dentro del array.

---

###  Resumen visual

| Método                            | Qué recorre              | Devuelve                | Ejemplo               |
| --------------------------------- | ------------------------ | ----------------------- | --------------------- |
| `for x in arr`                    | Filas o subarrays        | Arrays 1-D o 2-D        | `for x in arr:`       |
| `np.nditer(arr)`                  | Todos los elementos      | Escalares               | Iteración total       |
| `np.nditer(..., op_dtypes=['S'])` | Todos los elementos      | Convertidos a otro tipo | Temporales con buffer |
| `np.nditer(arr[:, ::2])`          | Subconjunto de elementos | Escalares               | Iteración con paso    |
| `np.ndenumerate(arr)`             | Elementos + índice       | (índice, valor)         | Con posición exacta   |

---

## <font color="red"> Actividad práctica 7</font>

1. Crea el array:

   ```python
   import numpy as np
   arr = np.array([[10, 20, 30], [40, 50, 60]])
   ```

   * Recorre el array con un `for` simple (deberías ver las filas).
   * Luego recorre **cada elemento** con bucles anidados.
   * Después, usa `np.nditer()` para hacerlo en una sola línea.

2. Crea un array 3-D con `np.arange(1, 13).reshape(2, 3, 2)`

   * Usa `np.ndenumerate()` para imprimir el índice y el valor.

3. Explica con tus palabras:

   * ¿Qué ventajas tiene usar `np.nditer()` frente a bucles anidados normales?
   * ¿En qué casos crees que sería útil `ndenumerate()`?


In [35]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60]])
for i in arr:
    print(i)
    for x in i:
        print(x)
for i in np.nditer(arr):
    print(i)

#Ejercicio 2
arr1 = np.arange(1,13).reshape(2,3,2)
print(arr1)
for i in np.ndenumerate(arr1):
    print(i)

print("Tiene la ventaja de que no tienes que hacer bucles dentro de bucles para recorrerlos")
print("Sería util usar ndenumerate() cuanod se quiera sacar tanto el valor como el indice ")

[10 20 30]
10
20
30
[40 50 60]
40
50
60
10
20
30
40
50
60
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 1, 0), np.int64(3))
((0, 1, 1), np.int64(4))
((0, 2, 0), np.int64(5))
((0, 2, 1), np.int64(6))
((1, 0, 0), np.int64(7))
((1, 0, 1), np.int64(8))
((1, 1, 0), np.int64(9))
((1, 1, 1), np.int64(10))
((1, 2, 0), np.int64(11))
((1, 2, 1), np.int64(12))
Tiene la ventaja de que no tienes que hacer bucles dentro de bucles para recorrerlos
Sería util usar ndenumerate() cuanod se quiera sacar tanto el valor como el indice 



# 🔝 Unir arrays en NumPy

En NumPy, **unir arrays** significa poner el contenido de dos o más arrays juntos en uno solo.

📘 Si vienes del mundo de las bases de datos (SQL), allí un *join* une tablas según una clave.
En NumPy, unimos arrays según sus **ejes (axes)**.

**Muy frecuente en preparación de datos**

Estas funciones se usan al:

* Combinar conjuntos de entrenamiento y validación.
* Unir columnas de características (`features`) o etiquetas (`labels`).

Ejemplo:

```python
X_full = np.concatenate((X_train, X_test))
y_full = np.concatenate((y_train, y_test))
```

👉 En proyectos de ML siempre hay momentos en que necesitas **fusionar o trocear matrices de datos**.


---

##  1. Concatenar arrays con `np.concatenate()`

La función `concatenate()` sirve para **unir arrays existentes a lo largo de un eje**.

📏 Si no indicas el eje, por defecto usa `axis=0` (filas).

### Ejemplo: unir dos arrays 1D

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]



---

### Ejemplo: unir dos arrays 2D por columnas (`axis=1`)

In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**Regla importante:**
Las dimensiones deben coincidir en todos los ejes excepto en el que estás concatenando.

---

##  2. Apilar arrays con `np.stack()`

“Apilar” (*stacking*) es muy parecido a concatenar, pero **crea un nuevo eje**.
En otras palabras, no une sobre un eje existente, sino que añade una nueva dimensión.

###  Ejemplo:


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


Aquí se ha creado un eje nuevo (columnas).
Si usamos `axis=0`, los arrays se apilarían uno encima del otro.
Si usamos `axis=1`, se apilan uno al lado del otro.

---

## 3. Funciones especiales para apilar más fácilmente

NumPy tiene versiones simplificadas de `stack()` para casos comunes:

| Función       | Qué hace                               | Eje |
| ------------- | -------------------------------------- | --- |
| `np.hstack()` | Une horizontalmente (filas → columnas) | 1   |
| `np.vstack()` | Une verticalmente (una sobre otra)     | 0   |
| `np.dstack()` | Une en profundidad (altura o “capas”)  | 2   |

---

### Ejemplo: `hstack()` (horizontal)

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)
# [1 2 3 4 5 6]

[1 2 3 4 5 6]


---

##### Ejemplo: `vstack()` (vertical)

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


---

#### Ejemplo: `dstack()` (profundidad)

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Esto se usa mucho en imágenes o datos 3D, donde cada capa representa algo distinto (por ejemplo, canales de color RGB).

---

### En resumen

| Método          | Crea nuevo eje | Dirección de unión            | Ejemplo visual                          |
| --------------- | -------------- | ----------------------------- | --------------------------------------- |
| `concatenate()` | ❌              | eje existente (por defecto 0) | `[1,2,3] + [4,5,6] → [1,2,3,4,5,6]`     |
| `stack()`       | ✅              | nuevo eje                     | crea matriz 2D o 3D                     |
| `hstack()`      | ❌              | horizontal (columnas)         | `[1,2,3]` + `[4,5,6]` → `[1,2,3,4,5,6]` |
| `vstack()`      | ❌              | vertical (filas)              | crea 2 filas                            |
| `dstack()`      | ✅              | profundidad (capas)           | útil en imágenes                        |

Perfecto 👌.
Aquí tienes una **actividad sencilla**, en el mismo formato y nivel que la que has mostrado, para cerrar la parte de *unión de arrays*:

---

## <font color="red">Actividad práctica 8</font>

1. Crea los siguientes arrays:

   ```python
   import numpy as np
   a = np.array([1, 2, 3])
   b = np.array([4, 5, 6])
   ```

   * Une los dos arrays con `np.concatenate()`.
   * Luego haz lo mismo con `np.stack((a, b), axis=1)` y observa la diferencia.
   * Imprime ambos resultados y sus formas (`.shape`).

---

2. Crea los arrays:

   ```python
   x = np.array([[1, 2], [3, 4]])
   y = np.array([[5, 6], [7, 8]])
   ```

   * Únelos horizontalmente con `np.hstack((x, y))`.
   * Únelos verticalmente con `np.vstack((x, y))`.
   * Comprueba con `.shape` cómo cambia la dimensión del array.

---

3. Explica con tus palabras:

   * ¿Qué diferencia hay entre `concatenate()` y `stack()`?
   * ¿En qué caso usarías `hstack()` o `vstack()` en lugar de `concatenate()`?

---



In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a,b))
print(arr)
arr1 = np.stack((a,b),axis=1)
print(arr1)
print(arr.shape,arr1.shape)
#Ejercicios2
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
xy = np.hstack((x,y))
print(xy)
yx = np.vstack((x,y))
print(yx)
print(xy.shape,yx.shape)

#Ejercicio 3
print("La diferencia entre concatenate y stack es que concatenate, Combina arrays a lo largo de un eje sin cambiar sus dimensiones y stack Apila arrays en un nuevo eje, aumentando la dimensión del resultado")
print("concatenate lo usaria para combinar tanto filas como columnas, hstack para unir horizontalmente y vstack verticalmente")


[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
(6,) (3, 2)
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2, 4) (4, 2)
La diferencia entre concatenate y stack es que concatenate, Combina arrays a lo largo de un eje sin cambiar sus dimensiones y stack Apila arrays en un nuevo eje, aumentando la dimensión del resultado



# 🔝 NumPy: Dividir arrays (*Splitting arrays*)

La **división de arrays** es la operación contraria a la unión (*joining*).
Mientras **unir (join)** combina varios arrays en uno solo, **dividir (split)** separa un array en varias partes más pequeñas.

➡️ **Muy frecuente en la preparación de datos para Machine Learning**

Estas funciones se usan para **separar datasets grandes** en varios subconjuntos, por ejemplo:

* Entrenamiento y prueba (`train` / `test`).
* Entrenamiento, validación y prueba (`train` / `val` / `test`).
* Particiones de datos para validación cruzada.

---

## 🔹 1. Dividir arrays 1D con `np.array_split()`

La función `np.array_split()` sirve para **dividir un array en varias partes**.
Se le indica:

1. El array que queremos dividir.
2. El número de partes.

### Ejemplo: dividir en 3 partes

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)

El resultado es una **lista** que contiene tres arrays separados.

---

### Ejemplo: dividir en 4 partes

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)

print(newarr)

Si el número de elementos no se reparte exactamente, NumPy ajusta las divisiones automáticamente desde el final.

 **Nota:**
Existe otra función llamada `split()`, pero **falla** si el número de elementos no encaja exactamente en las divisiones.
Por eso se recomienda usar **`array_split()`**.

---

## 2. Acceder a las partes del resultado

El resultado de `array_split()` es una lista.
Podemos acceder a cada parte igual que accedemos a los elementos de una lista normal:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])   # primera parte
print(newarr[1])   # segunda parte
print(newarr[2])   # tercera parte

---

## 3. Dividir arrays 2D

Funciona exactamente igual con arrays de dos dimensiones.

#### Ejemplo: dividir en tres arrays 2D


In [ ]:
import numpy as np

arr = np.array([
    [1, 2], [3, 4], [5, 6],
    [7, 8], [9, 10], [11, 12]
])

newarr = np.array_split(arr, 3)
print(newarr)

---

#### Ejemplo con más columnas


In [ ]:
import numpy as np

arr = np.array([
  [1, 2, 3], [4, 5, 6],
  [7, 8, 9], [10, 11, 12],
  [13, 14, 15], [16, 17, 18]
])

newarr = np.array_split(arr, 3)
print(newarr)

También devuelve tres arrays 2D, cada uno con dos filas.

---

## 4. Dividir según columnas (`axis=1`)

También puedes indicar **en qué eje** se hará la división:

* `axis=0` → por filas (por defecto)
* `axis=1` → por columnas

#### Ejemplo:

In [ ]:
import numpy as np

arr = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10, 11, 12],
  [13, 14, 15],
  [16, 17, 18]
])

newarr = np.array_split(arr, 3, axis=1)
print(newarr)

---

##  5. Alternativas: `hsplit()`, `vsplit()` y `dsplit()`

NumPy tiene funciones simplificadas para dividir arrays según la dirección del eje:

| Función       | Divide por            | Equivalente a |
| ------------- | --------------------- | ------------- |
| `np.hsplit()` | Columnas (horizontal) | `axis=1`      |
| `np.vsplit()` | Filas (vertical)      | `axis=0`      |
| `np.dsplit()` | Profundidad (capas)   | `axis=2`      |

##### Ejemplo: dividir horizontalmente (`hsplit`)

In [ ]:
import numpy as np

arr = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10, 11, 12],
  [13, 14, 15],
  [16, 17, 18]
])

newarr = np.hsplit(arr, 3)
print(newarr)

##  En resumen

| Método          | Qué hace                                        | Dirección           | Devuelve        |
| --------------- | ----------------------------------------------- | ------------------- | --------------- |
| `array_split()` | Divide arrays aunque no sean divisibles exactos | filas (por defecto) | Lista de arrays |
| `split()`       | Divide pero **requiere división exacta**        | filas               | Lista de arrays |
| `hsplit()`      | Divide por columnas                             | horizontal          | Lista de arrays |
| `vsplit()`      | Divide por filas                                | vertical            | Lista de arrays |
| `dsplit()`      | Divide en profundidad                           | 3D                  | Lista de arrays |

---

## <font color="red">Actividad práctica 9</font>

1. Crea el array:

   ```python
   import numpy as np
   arr = np.array([10, 20, 30, 40, 50, 60, 70])
   ```

   * Divide el array en **3 partes** usando `np.array_split()`.
   * Imprime cada parte por separado.

2. Crea el siguiente array 2D:

   ```python
   arr = np.array([
       [1, 2, 3, 4, 5, 6],
       [7, 8, 9, 10, 11, 12]
   ])
   ```

   * Divide el array horizontalmente con `np.hsplit(arr, 3)`.
   * Divide el array verticalmente con `np.vsplit(arr, 2)`.
   * Observa la diferencia de resultado.

3. Explica con tus palabras:

   * ¿Qué diferencia hay entre `split()` y `array_split()`?
   * ¿En qué se parecen `hstack()` / `hsplit()` y `vstack()` / `vsplit()`?


In [13]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
newrr = np.array_split(arr,3)
print(newrr[0],newrr[1],newrr[2])
#Ejercicio 2
ejer2 = np.array([
       [1, 2, 3, 4, 5, 6],
       [7, 8, 9, 10, 11, 12]
   ])
ejer2_1 = np.hsplit(ejer2,3)

ejer2_2 = np.vsplit(ejer2,2)
print(ejer2_2)
print(ejer2_1)

#Ejercicio3
print("Imprime de manera igualitaria, y array_split(), intenta dividir de manera igualitaria pero es mas flexible")
print("hstack() y hsplit() se usan para apilar y dividir horizontalmente, respectivamente, mientras que vstack() y vsplit() lo hacen verticalmente")

[10 20 30] [40 50] [60 70]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
Imprime de manera igualitaria, y array_split(), intenta dividir de manera igualitaria pero es mas flexible
hstack() y hsplit() se usan para apilar y dividir horizontalmente, respectivamente, mientras que vstack() y vsplit() lo hacen verticalmente



#  NumPy: Búsqueda en arrays (*Searching Arrays*)

NumPy permite **buscar valores dentro de un array** y obtener los **índices** donde se encuentran.
Esto resulta muy útil cuando queremos localizar elementos o analizar patrones en los datos.

**Importancia en ML**

Permite acceder de forma eficiente a datos:

* Seleccionar características (`X[:, [0, 3, 5]]`)
* Filtrar por rangos (`X[(X[:,0]>0.5) & (X[:,1]<1)]`)
* Reorganizar datos para entrenamiento en batch.

Saber usar **indexación NumPy avanzada** evita bucles y mejora la eficiencia de tus modelos.

---

## 🔹 1. Buscar elementos con `np.where()`

La función `where()` devuelve las posiciones (índices) donde se cumple una determinada condición.
El resultado es una **tupla** que contiene los índices coincidentes.

### Ejemplo: encontrar dónde está el valor 4

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


Esto significa que el número `4` aparece en los **índices 3, 5 y 6** del array.

---

### Ejemplo: encontrar los valores **pares**

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 7]),)


Estos son los índices donde el valor es par.

---

### Ejemplo: encontrar los valores **impares**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 1)

print(x)

Estos índices corresponden a los valores impares.

---

## 🔹 2. Buscar posiciones de inserción con `np.searchsorted()`

El método `searchsorted()` realiza una **búsqueda binaria** en un array **ordenado** y devuelve el índice donde debería insertarse un valor para mantener el orden.

### Ejemplo: dónde debería insertarse el valor 7

In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


**Explicación:**
El valor `7` debería colocarse en la **posición 1** para mantener el orden creciente del array.

---

### 🔸 Buscar desde la derecha

Por defecto, `searchsorted()` busca desde la izquierda.
Si quieres buscar desde la derecha, añade el parámetro `side='right'`.

In [27]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


Ahora indica que `7` se insertaría en el **índice 2** para mantener el orden, ya que el método busca desde el final.

---

### 🔸 Buscar varios valores a la vez

También puedes buscar **múltiples valores** indicando una lista o array.

In [24]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


Significa que:

* El `2` se insertaría en el índice `1`.
* El `4` en el índice `2`.
* El `6` en el índice `3`.

---

##  En resumen

| Función                                         | Qué hace                                                               | Devuelve        |
| ----------------------------------------------- | ---------------------------------------------------------------------- | --------------- |
| `np.where(condición)`                           | Devuelve los índices donde se cumple la condición                      | Tupla de arrays |
| `np.searchsorted(array, valor)`                 | Devuelve el índice donde se insertaría el valor para mantener el orden | Entero o array  |
| `np.searchsorted(array, valores, side='right')` | Igual, pero busca desde la derecha                                     | Entero o array  |

---

## <font color="red">Actividad práctica 10</font>

1. Crea el siguiente array:

   ```python
   import numpy as np
   arr = np.array([5, 10, 15, 10, 20, 10, 25])
   ```

   * Usa `np.where()` para encontrar todos los índices donde el valor sea **10**.
   * Imprime los índices resultantes.

---

2. Crea un nuevo array ordenado:

   ```python
   arr2 = np.array([3, 6, 9, 12, 15])
   ```

   * Usa `np.searchsorted(arr2, 10)` para ver en qué posición se insertaría el número **10**.
   * Usa `np.searchsorted(arr2, 10, side='right')` y compara los resultados.

---

3. Crea un array de varios valores:

   ```python
   arr3 = np.array([2, 4, 6, 8])
   ```

   * Usa `np.searchsorted(arr3, [3, 7, 9])`.
   * Explica qué significa cada índice obtenido.

---

4. **Reflexión:**

   * ¿Para qué tipo de tareas en Inteligencia Artificial o análisis de datos crees que puede ser útil `where()` o `searchsorted()`?
     *(Por ejemplo: localizar errores, clasificar datos o insertar nuevos registros ordenados)*

In [24]:
import numpy as np
arr = np.array([5, 10, 15, 10, 20, 10, 25])
print(np.where(arr == 10))
print(np.where(arr != 10))

#Ejercicio2
arr2 = np.array([3, 6, 9, 12, 15])
arr3 = np.searchsorted(arr2,10)
print(arr2)

arr4 =  np.searchsorted(arr2,10, side="right")
print(arr4)


#Ejercicio3
arr5 = np.array([2, 4, 6, 8])
print(np.searchsorted(arr5,[3,7,9]))
print("np.searchsorted() devuelve los índices donde los valores especificados pueden insertarse en el arreglo de manera que el orden quede intacto")


#Ejercicio 4
print("np.searchsorted() Si estás trabajando con grandes volúmenes de datos y necesitas hacer comparaciones de elementos con un arreglo ordenado y np.where(), para filtrado de datos, por ejemplo edad de las personas")

(array([1, 3, 5]),)
(array([0, 2, 4, 6]),)
[ 3  6  9 12 15]
3
[1 3 4]
np.searchsorted() devuelve los índices donde los valores especificados pueden insertarse en el arreglo de manera que el orden quede intacto
np.searchsorted() Si estás trabajando con grandes volúmenes de datos y necesitas hacer comparaciones de elementos con un arreglo ordenado y np.where(), para filtrado de datos, por ejemplo edad de las personas



# 🔝 NumPy: Ordenar arrays (*Sorting Arrays*)

**Ordenar** significa colocar los elementos de un array en un **orden determinado**.
Por ejemplo:

* Numéricamente (de menor a mayor o viceversa).
* Alfabéticamente (de la A a la Z o de la Z a la A).
* O incluso por valores booleanos (False antes que True).

En NumPy, los arrays (`ndarray`) tienen una función muy práctica llamada **`sort()`** que permite hacerlo fácilmente.

➡️ **Muy útil en análisis y evaluación**

* **`np.where()`** se usa para **localizar índices** que cumplen una condición (por ejemplo, errores de clasificación o máximos locales).
* **`np.sort()`** permite **ordenar probabilidades, distancias o errores** para obtener rankings o métricas (por ejemplo, en k-NN o para seleccionar los mayores pesos).
* **`np.searchsorted()`** se usa menos, pero es clave en operaciones de búsqueda eficiente en arrays ordenados.

Ejemplo:

```python
# Obtener los índices de las 3 predicciones más altas
top3 = np.argsort(predicciones)[-3:]
```

Fundamental para **evaluar modelos, interpretar resultados o aplicar reglas personalizadas.**

---

## 🔹 1. Ordenar arrays numéricos

El método `np.sort()` devuelve una **copia ordenada del array**, sin modificar el original.

### Ejemplo:

In [28]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


Nota:
El array original `arr` **no cambia**; `np.sort()` crea un nuevo array con los valores ordenados.

---

## 🔹 2. Ordenar arrays de cadenas (strings)

`np.sort()` también funciona con texto: los ordena alfabéticamente.

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

Ordena según el alfabeto (A → Z).
En inglés o español funciona igual siempre que las cadenas estén codificadas en ASCII o UTF-8.

---

## 🔹 3. Ordenar arrays booleanos

Los valores booleanos (`True` y `False`) también se pueden ordenar:

* `False` se considera **0**
* `True` se considera **1**

### Ejemplo:

In [29]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


---

## 🔹 4. Ordenar arrays bidimensionales (2D)

Cuando usamos `np.sort()` en un array 2D, **ordena cada fila de forma independiente**, manteniendo las dimensiones.

### Ejemplo:

In [30]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


quí, NumPy ha ordenado **cada fila** individualmente en orden ascendente.

---

##  En resumen

| Tipo de datos   | Resultado                | Observaciones                   |
| --------------- | ------------------------ | ------------------------------- |
| Numérico        | Orden ascendente         | `[0 1 2 3]`                     |
| Texto (strings) | Orden alfabético         | `['apple', 'banana', 'cherry']` |
| Booleano        | `False` antes que `True` | `[False, True, True]`           |
| 2D              | Ordena cada fila         | mantiene la forma original      |

---

### <font color="red">Actividad práctica 11</font>

1. Crea un array con los números `[5, 1, 8, 3, 7, 2]`

   * Ordénalo con `np.sort()`
   * Comprueba que el array original **no cambia**.

---

2. Crea un array de cadenas:

   ```python
   frutas = np.array(["pera", "naranja", "kiwi", "manzana"])
   ```

   * Ordénalo alfabéticamente con `np.sort(frutas)`
   * ¿Qué fruta aparece primero?

---

3. Crea un array booleano:

   ```python
   estados = np.array([True, False, False, True, True])
   ```

   * Ordénalo con `np.sort(estados)`
   * ¿Qué valor aparece al principio?

---

4. Crea el siguiente array 2D:

   ```python
   datos = np.array([[4, 9, 1], [8, 3, 5]])
   ```

   * Usa `np.sort(datos)`
   * Explica cómo ordena los valores y qué filas cambian.

---

5. **Reto adicional:**

   * ¿Cómo podrías ordenar un array 1D en **orden descendente** (de mayor a menor)?
     *(Pista: puedes combinar `np.sort()` con slicing inverso `[::-1]`)*

In [37]:
import numpy as np
arr = np.array([5,1,8,3,7,2])
np.sort(arr)
print(arr)

#Ejercicio 2
frutas = np.array(["pera", "naranja", "kiwi", "manzana"])
print(np.sort(frutas))
#Ejercicio 3
estados = np.array([True, False, False, True, True])
print(np.sort(estados),"aparecen primero los false")

#Ejercicio 4
datos = np.array([[4, 9, 1], [8, 3, 5]])
print(np.sort(datos))
print("Cambiar los valores dentro de cada [] ordenandolos")

#Ejercicio 5
array = np.array([6,5,4,3,2,1])
print(np.sort(array)[::-1])


[5 1 8 3 7 2]
['kiwi' 'manzana' 'naranja' 'pera']
[False False  True  True  True] aparecen primero los false
[[1 4 9]
 [3 5 8]]
Cambiar los valores dentro de cada [] ordenandolos
[6 5 4 3 2 1]



#  🔝 NumPy: Filtrar arrays (*Filter Arrays*)

Filtrar un array significa **obtener algunos elementos específicos** de un array existente para crear un **nuevo array** con ellos.

En otras palabras, nos quedamos solo con los valores que cumplen una condición.

**Imprescindible en ML**

En Machine Learning se usa constantemente para **preprocesar datos**:

* Quitar valores faltantes o erróneos.
* Seleccionar subconjuntos de datos (por ejemplo, solo filas con clase “1”).
* Aplicar máscaras sobre datasets grandes (por ejemplo, `X[y == 0]`).

Ejemplo real:

```python
X = X[y != -1]  # eliminar muestras con etiqueta desconocida
y = y[y != -1]
```

Este tipo de filtrado vectorizado es **la base del manejo eficiente de datos** con NumPy, pandas o frameworks como TensorFlow y PyTorch.


---

## 🔹 1. Filtrar usando una lista booleana

En NumPy, se puede filtrar un array usando una **lista de valores booleanos** (`True` o `False`).
Cada valor en la lista indica si el elemento del array original debe incluirse o no:

* `True` → el elemento se mantiene.
* `False` → el elemento se descarta.

---

### Ejemplo: crear un array con los elementos en las posiciones 0 y 2


In [31]:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


**Explicación:**
El nuevo array contiene los elementos de las posiciones donde la lista booleana tiene `True`:
índices **0** y **2** → `[41, 43]`.

---

## 🔹 2. Crear un filtro de forma manual (con un bucle)

Lo más común es crear esa lista booleana de forma automática según una **condición**.

---

### Ejemplo: valores mayores que 42

In [32]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Creamos una lista vacía
filter_arr = []

# Recorremos cada elemento del array
for element in arr:
  # Si el elemento es mayor que 42, añadimos True, si no, False
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


 Solo se mantienen los valores que cumplen la condición (> 42).

---

### Ejemplo: valores pares

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


---

## 🔹 3. Crear el filtro directamente (sin bucles)

NumPy permite aplicar condiciones **directamente sobre el array**, lo que hace el código mucho más corto y rápido.

En lugar de usar un bucle, simplemente escribimos la condición:

---

### Ejemplo: valores mayores que 42

In [34]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


---

### Ejemplo: valores pares

In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


**Ventaja:**
Este método es más rápido, más legible y aprovecha la vectorización de NumPy (sin necesidad de recorrer los elementos con un bucle `for`).

---

##  En resumen

| Método                   | Cómo funciona                                      | Ejemplo                     | Resultado                     |
| ------------------------ | -------------------------------------------------- | --------------------------- | ----------------------------- |
| Lista booleana manual    | Se indica `True` o `False` por cada elemento       | `[True, False, True]`       | Mantiene los elementos `True` |
| Filtro con bucle         | Crea una lista booleana según condición            | `x > 10` dentro de un `for` | Filtra según una regla        |
| Filtro directo con NumPy | Se aplica la condición directamente sobre el array | `arr[arr > 10]`             | Más simple y eficiente        |

---

### 💡 Consejo práctico

Puedes combinar condiciones con **operadores lógicos**:

* `&` (AND)
* `|` (OR)
* `~` (NOT)

Ejemplo:

```python
arr = np.array([10, 20, 30, 40, 50])
newarr = arr[(arr > 15) & (arr < 45)]
print(newarr)
# [20 30 40]
```

---

## <font color="red">Actividad práctica 12</font>

1. Crea un array:

   ```python
   import numpy as np
   edades = np.array([15, 18, 21, 16, 25, 30, 17])
   ```

   * Filtra los valores **mayores o iguales a 18** (mayores de edad).
   * Muestra el nuevo array.

---

2. Crea el array:

   ```python
   numeros = np.array([5, 12, 7, 18, 20, 3, 9])
   ```

   * Filtra solo los **valores pares**.
   * Luego filtra los **valores impares**.

---

3. Crea un array con temperaturas en ºC:

   ```python
   temperaturas = np.array([-2, 5, 12, 0, 18, 25, -1])
   ```

   * Filtra las temperaturas **mayores o iguales a 0** (temperaturas positivas).
   * Filtra las que estén **entre 10 y 20 grados**.

---

4. **Reflexiona:**

   * ¿Qué ventajas tiene usar filtros directos con NumPy frente a los bucles normales en Python?
   * ¿En qué tipo de análisis o proyectos de IA podría resultarte útil filtrar arrays?

In [56]:
import numpy as np
edades = np.array([15, 18, 21, 16, 25, 30, 17])
filter_arr = edades >= 18
newarr = edades[filter_arr]
print(filter_arr)
print(newarr)

#Ejercicio 2
numeros = np.array([5, 12, 7, 18, 20, 3, 9])
filtro = numeros % 2 == 0
filtro2 = numeros % 2 != 0
arraynuevo = numeros[filtro]
print(filtro)
print(arraynuevo)
arraynuevo1 = numeros[filtro2]
print(filtro2)
print(arraynuevo1)
#Ejercicio 3
temperaturas = np.array([-2, 5, 12, 0, 18, 25, -1])
filtro3 = temperaturas >= 0
arraynuevo3 = temperaturas[filtro3]
print(filtro3)
print(arraynuevo3)
filtro4 = (temperaturas > 10) & (temperaturas <20)
arraynuevo4 = temperaturas[filtro4]
print(filtro4)
print(arraynuevo4)
print("Usar filtros directos con NumPy es más eficiente y rápido que los bucles en Python, ya que NumPy está optimizado para operaciones vectorizadas y realiza cálculos a nivel de C")
print("Filtrar arrays es útil en IA para preprocesar datos, seleccionar subconjuntos relevantes, analizar series temporales, segmentar imágenes y elegir características importantes para modelos")

[False  True  True False  True  True False]
[18 21 25 30]
[False  True False  True  True False False]
[12 18 20]
[ True False  True False False  True  True]
[5 7 3 9]
[False  True  True  True  True  True False]
[ 5 12  0 18 25]
[False False  True False  True False False]
[12 18]
Usar filtros directos con NumPy es más eficiente y rápido que los bucles en Python, ya que NumPy está optimizado para operaciones vectorizadas y realiza cálculos a nivel de C
Filtrar arrays es útil en IA para preprocesar datos, seleccionar subconjuntos relevantes, analizar series temporales, segmentar imágenes y elegir características importantes para modelos


##  **Bibliografía y recursos de referencia**

El contenido y los ejemplos prácticos de este cuaderno están basados y adaptados del curso original de **NumPy** de [W3Schools](https://www.w3schools.com/python/numpy_intro.asp), un recurso introductorio ampliamente utilizado para el aprendizaje de programación científica en Python.

**Referencia principal:**

> W3Schools. (2025). *Python NumPy Tutorial*. Recuperado de
> [https://www.w3schools.com/python/numpy_intro.asp](https://www.w3schools.com/python/numpy_intro.asp)

**Adaptación docente:**

> Versión adaptada por el profesor Carlos Tessier (IES San Andrés) para el módulo
> *Programación de Inteligencia Artificial* del *Curso de Especialización en Inteligencia Artificial y Big Data (2025–26)*.

---